# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/web-development',
                'doc_host': 'https://nextrick.github.io',
                'git_url': 'https://github.com/nextrick/web-development',
                'lib_path': 'web_development'},
  'syms': {'web_development.core': {'web_development.core.foo': ('core.html#foo', 'web_development/core.py')}}}
